### ISSUE TITLE
Can't build with Xcode 12.5

### ISSUE THREAD

**Issue by armandsLa** [ninjasolutions/flutter_pusher#17]
Flutter pusher relies on `PusherSwift (7.2.0)` that uses an old version of `CryptoSwift`.  Xcode 12.5 has an error when building `CryptoSwift` prior to version `1.3.2`

The issue: https://github.com/krzyzanowskim/CryptoSwift/issues/864#issuecomment-829444430

**Comment by soewaiyanmyowin** [comment]
same here! I am stuck right now .Any work around for this? pls
@armandsLa  @josh-burton @genert

**Comment by josh-burton** [comment]
@soewaiyanmyowin this repo doesn't seem maintained but you can use the branch of this PR directly: https://github.com/ninjasolutions/flutter_pusher/pull/16

**Comment by soewaiyanmyowin** [comment]
> @soewaiyanmyowin this repo doesn't seem maintained but you can use the branch of this PR directly: https://github.com/ninjasolutions/flutter_pusher/pull/16

Wow! It worked. didn't know that one. Really really appreciate that . Thanks in advance.

**Comment by genert** [comment]
Sorry for such late response, I was away from Flutter development for more than a year.

Merged the PR #16 (Thank you @josh-burton).

Closing this issue as it is resolved now.
