### ISSUE TITLE
Please let me maintain this repo

### ISSUE THREAD

**Issue by tshedor** [ninjasolutions/flutter_pusher#19]
## 🏗 Enhancement Proposal

This repo has been abandoned by maintainers. Please give me write access and pub.dev permissions to publish updates. 

### Pitch

You started this repo because `pusher_flutter` wasn't being maintained despite my PR (apptreesoftware/pusher_flutter#5). You left a comment that you were taking my PR code and [making your own package](https://github.com/apptreesoftware/pusher_flutter/pull/5#issuecomment-528822811). You've expanded the functionality and done well. I really appreciate it. Please don't let this package meet the same fate as the old package.

There have been several high-profile changes in Flutter recently, and while they don't require significant changes, they do require _some_ changes. (#14 ).

I maintain [Brick](https://github.com/GetDutchie/brick), [Datadog Flutter](https://github.com/GetDutchie/datadog_flutter), and [Flutter Image Form Field](https://github.com/tshedor/flutter_image_form_field). 

As a maintainer, I know how weary looking after stale code can be. Especially code you don't use. But people still use it, and the egalitarian spirit of open source would see you passing that torch to those of us that want to communally use this code. 

I know how this dance goes, and when I'm done, I'll throw in the towel and seek new maintainer.

Please let us, the community, maintain this repo. You can reach me directly at tim dot shedor at dutchie dot com.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by tshedor** [comment]
@genert friendly nudge here

**Comment by Josiassejod1** [comment]
@genert nudge

**Comment by genert** [comment]
@tshedor I added you as collaborator to this project. Please let me know if you need anything.
