### ISSUE TITLE
Unable to run app - missing method on Android

### ISSUE THREAD

**Issue by josh-burton** [ninjasolutions/flutter_pusher#2]
## 🐛 Bug Report

When trying to run my app after adding this plugin I'm getting an error with the Android plugin:

```
.pub-cache/hosted/pub.dartlang.org/flutter_pusher-1.0.1/android/src/main/java/com/ninjasolutions/pusher/PusherPlugin.java:382: error: cannot find symbol
            channel.trigger(eventName, "{}");
                   ^
  symbol:   method trigger(String,String)
  location: variable channel of type Channel
```

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by genert** [comment]
Thank you for the PR. Made a new release, `1.0.2` has the fix included.
